/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_alibaba_mpc4j_s2pc_upso_ucpsi_sj23_pmt_Sj23PmtUcpsiNativeUtils */

#ifndef _Included_edu_alibaba_mpc4j_s2pc_upso_ucpsi_sj23_pmt_Sj23PmtUcpsiNativeUtils
#define _Included_edu_alibaba_mpc4j_s2pc_upso_ucpsi_sj23_pmt_Sj23PmtUcpsiNativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_alibaba_mpc4j_s2pc_upso_ucpsi_sj23_pmt_Sj23PmtUcpsiNativeUtils
 * Method:    genEncryptionParameters
 * Signature: (IJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_alibaba_mpc4j_s2pc_upso_ucpsi_sj23_pmt_Sj23PmtUcpsiNativeUtils_genEncryptionParameters
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     edu_alibaba_mpc4j_s2pc_upso_ucpsi_sj23_pmt_Sj23PmtUcpsiNativeUtils
 * Method:    keyGen
 * Signature: ([B)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_edu_alibaba_mpc4j_s2pc_upso_ucpsi_sj23_pmt_Sj23PmtUcpsiNativeUtils_keyGen
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     edu_alibaba_mpc4j_s2pc_upso_ucpsi_sj23_pmt_Sj23PmtUcpsiNativeUtils
 * Method:    computeEncryptedPowers
 * Signature: ([B[BLjava/util/List;[[I[II)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_edu_alibaba_mpc4j_s2pc_upso_ucpsi_sj23_pmt_Sj23PmtUcpsiNativeUtils_computeEncryptedPowers
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jobject, jobjectArray, jintArray, jint);

/*
 * Class:     edu_alibaba_mpc4j_s2pc_upso_ucpsi_sj23_pmt_Sj23PmtUcpsiNativeUtils
 * Method:    naiveComputeMatches
 * Signature: ([B[B[[JLjava/util/List;[J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_alibaba_mpc4j_s2pc_upso_ucpsi_sj23_pmt_Sj23PmtUcpsiNativeUtils_naiveComputeMatches
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jobjectArray, jobject, jlongArray);

/*
 * Class:     edu_alibaba_mpc4j_s2pc_upso_ucpsi_sj23_pmt_Sj23PmtUcpsiNativeUtils
 * Method:    generateQuery
 * Signature: ([B[B[B[[J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_edu_alibaba_mpc4j_s2pc_upso_ucpsi_sj23_pmt_Sj23PmtUcpsiNativeUtils_generateQuery
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jobjectArray);

/*
 * Class:     edu_alibaba_mpc4j_s2pc_upso_ucpsi_sj23_pmt_Sj23PmtUcpsiNativeUtils
 * Method:    decodeReply
 * Signature: ([B[B[B)[J
 */
JNIEXPORT jlongArray JNICALL Java_edu_alibaba_mpc4j_s2pc_upso_ucpsi_sj23_pmt_Sj23PmtUcpsiNativeUtils_decodeReply
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
