/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_alibaba_mpc4j_s2pc_pir_index_xpir_XPirNativeServer */

#ifndef _Included_edu_alibaba_mpc4j_s2pc_pir_index_xpir_XPirNativeServer
#define _Included_edu_alibaba_mpc4j_s2pc_pir_index_xpir_XPirNativeServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_alibaba_mpc4j_s2pc_pir_index_xpir_XPirNativeServer
 * Method:    transformToNttForm
 * Signature: ([BLjava/util/ArrayList;)Ljava/util/ArrayList;
 */
[[maybe_unused]] JNIEXPORT jobject JNICALL Java_edu_alibaba_mpc4j_s2pc_pir_index_xpir_XPirNativeServer_transformToNttForm
  (JNIEnv *, jclass, jbyteArray, jobject);

/*
 * Class:     edu_alibaba_mpc4j_s2pc_pir_index_xpir_XPirNativeServer
 * Method:    generateReply
 * Signature: ([BLjava/util/ArrayList;Ljava/util/ArrayList;[I)Ljava/util/ArrayList;
 */
[[maybe_unused]] JNIEXPORT jobject JNICALL Java_edu_alibaba_mpc4j_s2pc_pir_index_xpir_XPirNativeServer_generateReply
  (JNIEnv *, jclass, jbyteArray, jobject, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
