/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_alibaba_mpc4j_s2pc_pir_index_xpir_XPirNativeParams */

#ifndef _Included_edu_alibaba_mpc4j_s2pc_pir_index_xpir_XPirNativeParams
#define _Included_edu_alibaba_mpc4j_s2pc_pir_index_xpir_XPirNativeParams
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_alibaba_mpc4j_s2pc_pir_index_xpir_XPirNativeParams
 * Method:    genEncryptionParameters
 * Signature: (IJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_alibaba_mpc4j_s2pc_pir_index_xpir_XPirNativeParams_genEncryptionParameters
  (JNIEnv *, jclass, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
