/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_alibaba_mpc4j_s2pc_pir_index_xpir_XPirNativeClient */

#ifndef _Included_edu_alibaba_mpc4j_s2pc_pir_index_xpir_XPirNativeClient
#define _Included_edu_alibaba_mpc4j_s2pc_pir_index_xpir_XPirNativeClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_alibaba_mpc4j_s2pc_pir_index_xpir_XPirNativeClient
 * Method:    generateQuery
 * Signature: ([B[B[B[I)Ljava/util/ArrayList;
 */
[[maybe_unused]] JNIEXPORT jobject JNICALL Java_edu_alibaba_mpc4j_s2pc_pir_index_xpir_XPirNativeClient_generateQuery
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jintArray);

/*
 * Class:     edu_alibaba_mpc4j_s2pc_pir_index_xpir_XPirNativeClient
 * Method:    decodeReply
 * Signature: ([B[BLjava/util/ArrayList;I)[J
 */
[[maybe_unused]] JNIEXPORT jlongArray JNICALL Java_edu_alibaba_mpc4j_s2pc_pir_index_xpir_XPirNativeClient_decodeReply
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jobject, jint);

/*
 * Class:     edu_alibaba_mpc4j_s2pc_pir_index_xpir_XPirNativeClient
 * Method:    keyGeneration
 * Signature: ([B)Ljava/util/List;
 */
[[maybe_unused]] JNIEXPORT jobject JNICALL Java_edu_alibaba_mpc4j_s2pc_pir_index_xpir_XPirNativeClient_keyGeneration
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
