/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_alibaba_mpc4j_common_tool_bitmatrix_NativeBitMatrix */

#ifndef _Included_edu_alibaba_mpc4j_common_tool_bitmatrix_NativeBitMatrix
#define _Included_edu_alibaba_mpc4j_common_tool_bitmatrix_NativeBitMatrix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_alibaba_mpc4j_common_tool_bitmatrix_NativeBitMatrix
 * Method:    nativeTranspose
 * Signature: ([BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_alibaba_mpc4j_common_tool_bitmatrix_NativeBitMatrix_nativeTranspose
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
