/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_alibaba_mpc4j_s2pc_pso_upsi_cmg21_Cmg21UpsiNativeServer */

#ifndef _Included_edu_alibaba_mpc4j_s2pc_pso_upsi_cmg21_Cmg21UpsiNativeServer
#define _Included_edu_alibaba_mpc4j_s2pc_pso_upsi_cmg21_Cmg21UpsiNativeServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_alibaba_mpc4j_s2pc_pso_upsi_cmg21_Cmg21UpsiNativeServer
 * Method:    computeEncryptedPowers
 * Signature: (Ljava/util/List;[B[B[[I[II)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_edu_alibaba_mpc4j_s2pc_pso_upsi_cmg21_Cmg21UpsiNativeServer_computeEncryptedPowers
  (JNIEnv *, jclass, jobject, jbyteArray, jbyteArray, jobjectArray, jintArray, jint);

/*
 * Class:     edu_alibaba_mpc4j_s2pc_pso_upsi_cmg21_Cmg21UpsiNativeServer
 * Method:    computeMatches
 * Signature: ([[JLjava/util/List;[B[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_alibaba_mpc4j_s2pc_pso_upsi_cmg21_Cmg21UpsiNativeServer_computeMatches
  (JNIEnv *, jclass, jobjectArray, jobject, jbyteArray, jbyteArray, jint);

/*
 * Class:     edu_alibaba_mpc4j_s2pc_pso_upsi_cmg21_Cmg21UpsiNativeServer
 * Method:    computeMatchesNaiveMethod
 * Signature: ([[JLjava/util/List;[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_alibaba_mpc4j_s2pc_pso_upsi_cmg21_Cmg21UpsiNativeServer_computeMatchesNaiveMethod
  (JNIEnv *, jclass, jobjectArray, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
