/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_alibaba_mpc4j_common_tool_polynomial_zp_NtlTreeZpPoly */

#ifndef _Included_edu_alibaba_mpc4j_common_tool_polynomial_zp_NtlTreeZpPoly
#define _Included_edu_alibaba_mpc4j_common_tool_polynomial_zp_NtlTreeZpPoly
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_alibaba_mpc4j_common_tool_polynomial_zp_NtlTreeZpPoly
 * Method:    nativeTreeEvaluate
 * Signature: ([B[[B[[B)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_edu_alibaba_mpc4j_common_tool_polynomial_zp_NtlTreeZpPoly_nativeTreeEvaluate
  (JNIEnv *, jclass, jbyteArray, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
