/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_alibaba_mpc4j_common_tool_polynomial_gf2x_NtlNativeGf2xPoly */

#ifndef _Included_edu_alibaba_mpc4j_common_tool_polynomial_gf2x_NtlNativeGf2xPoly
#define _Included_edu_alibaba_mpc4j_common_tool_polynomial_gf2x_NtlNativeGf2xPoly
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_alibaba_mpc4j_common_tool_polynomial_gf2x_NtlNativeGf2xPoly
 * Method:    interpolate
 * Signature: ([BII[[B[[B)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_edu_alibaba_mpc4j_common_tool_polynomial_gf2x_NtlNativeGf2xPoly_interpolate
  (JNIEnv *, jclass, jbyteArray, jint, jint, jobjectArray, jobjectArray);

/*
 * Class:     edu_alibaba_mpc4j_common_tool_polynomial_gf2x_NtlNativeGf2xPoly
 * Method:    rootInterpolate
 * Signature: ([BII[[B[B)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_edu_alibaba_mpc4j_common_tool_polynomial_gf2x_NtlNativeGf2xPoly_rootInterpolate
  (JNIEnv *, jclass, jbyteArray, jint, jint, jobjectArray, jbyteArray);

/*
 * Class:     edu_alibaba_mpc4j_common_tool_polynomial_gf2x_NtlNativeGf2xPoly
 * Method:    singleEvaluate
 * Signature: ([BI[[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_alibaba_mpc4j_common_tool_polynomial_gf2x_NtlNativeGf2xPoly_singleEvaluate
  (JNIEnv *, jclass, jbyteArray, jint, jobjectArray, jbyteArray);

/*
 * Class:     edu_alibaba_mpc4j_common_tool_polynomial_gf2x_NtlNativeGf2xPoly
 * Method:    evaluate
 * Signature: ([BI[[B[[B)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_edu_alibaba_mpc4j_common_tool_polynomial_gf2x_NtlNativeGf2xPoly_evaluate
  (JNIEnv *, jclass, jbyteArray, jint, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
